### ISSUE TITLE
Continuous Refreshing on Reports Page

### ISSUE THREAD

**Issue by WDKevin** [CodeAtCode/Woocommerce-Taxonomy-Report#2]
I've gone to the Integration tab and selected "product tags" to get reports. After that I go to the reports page and I click the Product Tags tab. Once on that page it just continuously refreshes or redirects the page over and over. It's the same page being loaded every time but it doesn't stop refreshing until I click stop. It also loses my options I chose after the first refresh so I'm not able to actually see any of the reports I want.

**Comment by Mte90** [comment]
I will try locally to see what' happening.

**Comment by Mte90** [comment]
Bug confirmed, I am working on it.

**Comment by Mte90** [comment]
I am releasing a new version with the fix on the wordpress repo.
