### ISSUE TITLE
Let store manager view reports

### ISSUE THREAD

**Issue by Wikisaqui** [CodeAtCode/Woocommerce-Taxonomy-Report#4]
Hello,

Is there a way to allow users with the woocommerce "store manager" profile to see the taxonomy reports?

Thanks

**Comment by Mte90** [comment]
Hi you need to change the line https://github.com/CodeAtCode/Woocommerce-Taxonomy-Report/blob/master/admin/includes/WC_Integration_TReport.php#L85 instead of `manage_options` needs to be `manage_woocommerce`.

**Comment by Mte90** [comment]
Released a new version also on the WP repo.
